version: 0.1.{build}
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
clone_depth: 1
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
- ps: >-
    .\nuget.exe restore

build:
  verbosity: minimal
test: off